#!/usr/bin/env node
// GENERATED by npm run build:burst from scripts/burst/burst.ts and core.ts. Do not edit; CI fails if it is stale.

// scripts/burst/burst.ts
import { writeFile } from "node:fs/promises";
import { parseArgs } from "node:util";

// scripts/burst/core.ts
var DEFAULTS = {
  rows: 40,
  seatsPerRow: 50,
  perUserLimit: 4,
  concurrency: 256,
  requests: 2e4,
  users: 5e3,
  pairShare: 0.2,
  hotSeats: 6,
  hotUsers: 500,
  retryGroups: 100,
  retryCopies: 5,
  keyReuseGroups: 50,
  limitUsers: 20,
  limitParallel: 10,
  crossedPairs: 50,
  spoofs: 50,
  foreignCancels: 50,
  pollMs: 250,
  metrics: true
};
var SCENARIOS = [
  "hot",
  "stampede",
  "retry",
  "keyreuse",
  "limit",
  "crossed",
  "spoof",
  "foreign"
];
var SLOWEST = 5;
var MAX_ATTEMPTS = 10;
function rowLabel(index) {
  let label = "";
  let i = index;
  do {
    label = String.fromCharCode(65 + i % 26) + label;
    i = Math.floor(i / 26) - 1;
  } while (i >= 0);
  return label;
}
function rng(seed) {
  let a = seed >>> 0;
  return () => {
    a = a + 1831565813 >>> 0;
    let t = a;
    t = Math.imul(t ^ t >>> 15, t | 1);
    t ^= t + Math.imul(t ^ t >>> 7, t | 61);
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
}
function zipf(n2, s, rand) {
  const cdf = new Float64Array(n2);
  let acc = 0;
  for (let k = 0; k < n2; k++) cdf[k] = acc += 1 / (k + 1) ** s;
  return () => {
    const u = rand() * acc;
    let lo = 0;
    let hi = n2 - 1;
    while (lo < hi) {
      const mid = lo + hi >> 1;
      if (cdf[mid] < u) lo = mid + 1;
      else hi = mid;
    }
    return lo;
  };
}
function quantile(sorted, q) {
  if (!sorted.length) return 0;
  return sorted[Math.min(sorted.length - 1, Math.max(0, Math.ceil(q * sorted.length) - 1))];
}
var sleep = (ms2, signal) => new Promise((resolve) => {
  if (signal?.aborted) return resolve();
  const onAbort = () => {
    clearTimeout(t);
    resolve();
  };
  const t = setTimeout(() => {
    signal?.removeEventListener("abort", onAbort);
    resolve();
  }, ms2);
  signal?.addEventListener("abort", onAbort, { once: true });
});
var Semaphore = class {
  free;
  waiters = [];
  constructor(n2) {
    this.free = n2;
  }
  get busy() {
    return this.waiters.length;
  }
  async acquire() {
    if (this.free > 0) this.free--;
    else await new Promise((r) => this.waiters.push(r));
    let done = false;
    return () => {
      if (done) return;
      done = true;
      const next = this.waiters.shift();
      if (next) next();
      else this.free++;
    };
  }
};
function parseMetrics(text) {
  const m = /* @__PURE__ */ new Map();
  for (const line of text.split("\n")) {
    if (!line || line.startsWith("#")) continue;
    const i = line.lastIndexOf(" ");
    m.set(line.slice(0, i), Number(line.slice(i + 1)));
  }
  return m;
}
function reserveCounters(m) {
  const out = /* @__PURE__ */ new Map();
  for (const [k, v] of m) {
    const hit = /^fdfs_reserve_responses_total\{outcome="([^"]+)"\}$/.exec(k);
    if (hit) out.set(hit[1], v);
  }
  return out;
}
var bump = (rec, k, n2 = 1) => rec[k] = (rec[k] ?? 0) + n2;
function planSeats(o, exactNeeded) {
  const all = [];
  const score = /* @__PURE__ */ new Map();
  for (let r = 0; r < o.rows; r++) {
    for (let s = 1; s <= o.seatsPerRow; s++) {
      const label = `${rowLabel(r)}${s}`;
      all.push(label);
      const rowDist = Math.abs(r - (o.rows - 1) * 0.6) / Math.max(1, o.rows);
      const seatDist = Math.abs(s - (o.seatsPerRow + 1) / 2) / Math.max(1, o.seatsPerRow);
      score.set(label, rowDist + seatDist);
    }
  }
  const front = [...all].sort((a, b) => {
    const ra = a.replace(/\d+$/, "");
    const rb = b.replace(/\d+$/, "");
    const rowCmp = ra.length - rb.length || ra.localeCompare(rb);
    if (rowCmp) return rowCmp;
    const c2 = (o.seatsPerRow + 1) / 2;
    return Math.abs(Number(a.slice(ra.length)) - c2) - Math.abs(Number(b.slice(rb.length)) - c2);
  });
  const hot = all.includes("A12") ? ["A12"] : [];
  for (const s of front) {
    if (hot.length >= o.hotSeats) break;
    if (!hot.includes(s)) hot.push(s);
  }
  const rest = all.filter((s) => !hot.includes(s)).sort((a, b) => score.get(a) - score.get(b));
  if (exactNeeded > rest.length - 1) {
    throw new Error(
      `the hall is too small: the exact scenarios need ${exactNeeded} seats and the crowd at least 1`
    );
  }
  const exact = rest.slice(rest.length - exactNeeded).reverse();
  const crowd = rest.slice(0, rest.length - exactNeeded);
  return { all, hot: hot.slice(0, o.hotSeats), crowd, exact };
}
function exactSeatsNeeded(o) {
  return o.keyReuseGroups * 2 + o.limitUsers * o.limitParallel + o.crossedPairs * 2 + o.spoofs + o.foreignCancels;
}
function plannedRequests(o) {
  return o.hotUsers + o.requests + o.retryGroups * o.retryCopies + o.keyReuseGroups * 3 + o.limitUsers * o.limitParallel + o.crossedPairs * 2 + o.spoofs + o.foreignCancels * 2;
}
function usersNeeded(o) {
  return o.hotUsers + o.users + o.retryGroups + o.keyReuseGroups + o.limitUsers + o.crossedPairs * 2 + o.spoofs + o.foreignCancels * 2;
}
async function runBurst(input) {
  const o = { ...DEFAULTS, ...input };
  const base2 = o.base.replace(/\/+$/, "");
  const status = (line) => o.onStatus?.(line);
  const signal = o.signal;
  const seed = Date.now();
  const rand = rng(seed);
  const run = `b${seed.toString(36)}${Math.floor(rand() * 1296).toString(36)}`;
  const seats = planSeats(o, exactSeatsNeeded(o));
  const outcomes = {};
  const httpStatus = { "2xx": 0, "4xx": 0, "429": 0, "5xx": 0, network: 0 };
  const latencies = [];
  let reserveRequests = 0;
  let retries = 0;
  let resent = 0;
  let droppedAttempts = 0;
  let unanswered = 0;
  let netMin = Infinity;
  let netMax = 0;
  let sent = 0;
  const networkErrors = [];
  const slowest = [];
  let done = 0;
  const pool = new Semaphore(Math.max(1, o.concurrency));
  let inFlight = 0;
  async function send(method, path, init = {}) {
    const requestId = `${run}-${++sent}`;
    const headers = { "x-request-id": requestId };
    if (init.bearer) headers.authorization = `Bearer ${init.bearer}`;
    if (init.key) headers["idempotency-key"] = init.key;
    if (init.body !== void 0) headers["content-type"] = "application/json";
    if (signal?.aborted) throw new DOMException("The burst was stopped", "AbortError");
    const t02 = performance.now();
    try {
      const res = await fetch(`${base2}${path}`, {
        method,
        headers,
        body: init.body === void 0 ? void 0 : JSON.stringify(init.body)
      });
      const text = await res.text();
      const ms2 = performance.now() - t02;
      let body = null;
      try {
        body = text ? JSON.parse(text) : null;
      } catch {
        body = text;
      }
      const code = body?.error?.code;
      const outcome = res.status === 201 ? res.headers.get("idempotent-replayed") === "true" ? "replayed" : "created" : code ?? `http_${res.status}`;
      const retryAfter = Number(res.headers.get("retry-after")) || 0;
      return { status: res.status, outcome, body, ms: ms2, requestId, retryAfter };
    } catch (err) {
      const ms2 = performance.now() - t02;
      const cause = err.cause;
      const why = cause?.code ?? cause?.message ?? err.message;
      if (networkErrors.length < 5 && !networkErrors.some((e) => e.startsWith(why))) {
        networkErrors.push(
          `${why} after ${Math.round(ms2)}ms (${method} ${path.replace(/[0-9a-f-]{36}/, ":id")})`
        );
      }
      netMin = Math.min(netMin, ms2);
      netMax = Math.max(netMax, ms2);
      return { status: 0, outcome: "network_error", body: why, ms: ms2, requestId };
    }
  }
  const tally = (r, reserve2) => {
    done++;
    if (r.status === 0) httpStatus.network++;
    else if (r.status === 429) httpStatus["429"]++;
    else if (r.status >= 500) httpStatus["5xx"]++;
    else if (r.status >= 400) httpStatus["4xx"]++;
    else httpStatus["2xx"]++;
    if (reserve2) {
      reserveRequests++;
      if (r.status === 0) droppedAttempts++;
      else {
        bump(outcomes, r.outcome);
        latencies.push(r.ms);
        if (slowest.length < SLOWEST || r.ms > slowest.at(-1).ms) {
          slowest.push({ requestId: r.requestId, ms: r.ms, outcome: r.outcome });
          slowest.sort((a, b) => b.ms - a.ms);
          slowest.length = Math.min(slowest.length, SLOWEST);
        }
      }
    }
  };
  async function call(method, path, init, reserve2) {
    let failedBefore = false;
    for (let attempt = 0; ; attempt++) {
      const release = await pool.acquire();
      inFlight++;
      let r;
      try {
        r = await send(method, path, init);
      } finally {
        inFlight--;
        release();
      }
      tally(r, reserve2);
      const retryable = r.status === 429 || r.status === 503 || r.status === 0;
      r.afterFailure = failedBefore;
      if (!retryable || attempt >= MAX_ATTEMPTS - 1 || signal?.aborted) {
        if (r.status === 0) unanswered++;
        return r;
      }
      if (r.status !== 429) failedBefore = true;
      retries++;
      const backoff = Math.max((r.retryAfter ?? 0) * 1e3, Math.min(15e3, 500 * 2 ** attempt));
      await sleep(backoff * (0.75 + rand() / 2), signal);
    }
  }
  const name = o.showName ?? `Burst ${new Date(seed).toISOString().slice(0, 19).replace("T", " ")}`;
  status(`creating show "${name}" (${seats.all.length.toLocaleString("en")} seats)\u2026`);
  const created = await send("POST", "/shows", {
    bearer: o.adminKey,
    body: {
      name,
      seats: seats.all,
      price_paise: 25e3,
      per_user_limit: o.perUserLimit,
      hold_ttl_seconds: null,
      ephemeral: true
    }
  });
  if (created.status !== 201) {
    throw new Error(
      `could not create the show: HTTP ${created.status} ${created.outcome}` + (created.status === 401 || created.status === 403 ? " (check the admin key)" : "")
    );
  }
  const made = created.body;
  const show = { id: made.id, name: made.name, total_seats: made.total_seats };
  o.onShow?.(show);
  const showPath = `/shows/${show.id}`;
  const need = usersNeeded(o);
  status(`minting ${need.toLocaleString("en")} tokens\u2026`);
  const users = [];
  for (let start = 1; users.length < need; ) {
    const count = Math.min(1e4, need - users.length);
    const r = await send("POST", "/auth/tokens", { body: { count, prefix: run, start } });
    if (r.status !== 200) throw new Error(`could not mint tokens: HTTP ${r.status} ${r.outcome}`);
    for (const t of r.body.tokens) {
      users.push({ id: t.user_id, token: t.token });
    }
    start += count;
  }
  let nextUser = 0;
  const takeUsers = (n2) => users.slice(nextUser, nextUser += n2);
  let nextExact = 0;
  const takeSeats = (n2) => seats.exact.slice(nextExact, nextExact += n2);
  const instanceNow = async () => {
    const r = await send("GET", "/ops/summary");
    const b = r.body;
    return r.status === 200 && b?.instance && b.started_at ? { instance: b.instance, started_at: b.started_at } : null;
  };
  const serverBefore = await instanceNow();
  let metricsBefore = null;
  if (o.metrics) {
    const m = await fetch(`${base2}/metrics`, { signal }).catch(() => null);
    metricsBefore = m?.ok ? reserveCounters(parseMetrics(await m.text())) : null;
    if (!metricsBefore) status("note: /metrics unreachable; skipping the metrics diff");
  }
  const scen = Object.fromEntries(SCENARIOS.map((s) => [s, {}]));
  const granted = [];
  const failures = Object.fromEntries(
    SCENARIOS.map((s) => [s, []])
  );
  const fail = (s, msg) => {
    if (failures[s].length < 5) failures[s].push(msg);
    else if (failures[s].length === 5) failures[s].push("\u2026");
  };
  const key = () => crypto.randomUUID();
  const reserve = async (s, u, seatList, opts2 = {}) => {
    const r = await call(
      "POST",
      `${showPath}/reserve`,
      { bearer: u.token, key: opts2.key ?? key(), body: { seats: seatList, ...opts2.extra } },
      true
    );
    r.sharedKey = opts2.shared === true;
    if (r.outcome === "replayed" && !r.sharedKey && !r.afterFailure) resent++;
    const won = isWin(r);
    bump(scen[s], won ? "created" : r.outcome);
    if (won) granted.push({ ...r.body, scenario: s });
    return r;
  };
  const isWin = (r) => r.outcome === "created" || r.outcome === "replayed" && (r.afterFailure === true || !r.sharedKey);
  const idOf = (r) => r.body?.reservation_id;
  const tasks = [];
  const hotWanted = /* @__PURE__ */ new Set();
  for (const u of takeUsers(seats.hot.length ? o.hotUsers : 0)) {
    const seat = rand() < 0.5 ? seats.hot[0] : seats.hot[Math.floor(rand() * seats.hot.length)];
    hotWanted.add(seat);
    tasks.push(async () => void await reserve("hot", u, [seat]));
  }
  const crowd = takeUsers(o.users);
  const pick = zipf(seats.crowd.length, 0.9, rand);
  for (let i = 0; i < o.requests; i++) {
    const u = crowd[Math.floor(rand() * crowd.length)];
    const a = seats.crowd[pick()];
    let want = [a];
    if (rand() < o.pairShare && seats.crowd.length > 1) {
      let b = seats.crowd[pick()];
      for (let tries = 0; b === a && tries < 5; tries++) b = seats.crowd[pick()];
      if (b !== a) want = [a, b];
    }
    tasks.push(async () => void await reserve("stampede", u, want));
  }
  for (const u of takeUsers(o.retryGroups)) {
    const k = key();
    const want = [seats.crowd[pick()]];
    tasks.push(async () => {
      const rs = await Promise.all(
        Array.from(
          { length: o.retryCopies },
          () => reserve("retry", u, want, { key: k, shared: true })
        )
      );
      const replay = rs.find((r) => r.outcome === "replayed");
      if (replay && !rs.some(isWin)) {
        resent++;
        granted.push({ ...replay.body, scenario: "retry" });
      }
      const ids = new Set(rs.filter((r) => r.status === 201).map(idOf));
      const createdN = rs.filter((r) => r.outcome === "created").length;
      const declined = rs.filter((r) => r.status === 409).length;
      if (createdN > 1) fail("retry", `key ${k}: ${createdN} copies created`);
      if (ids.size > 1)
        fail("retry", `key ${k}: copies returned ${ids.size} different reservations`);
      if (createdN === 1 && declined > 0) {
        fail("retry", `key ${k}: created once, yet ${declined} copies were declined, not replayed`);
      }
    });
  }
  for (const u of takeUsers(o.keyReuseGroups)) {
    const [x, y] = takeSeats(2);
    tasks.push(async () => {
      const k = key();
      const first = await reserve("keyreuse", u, [x], { key: k });
      if (!isWin(first)) {
        return fail("keyreuse", `${u.id}: first request ${first.outcome}`);
      }
      const other = await reserve("keyreuse", u, [y], { key: k, shared: true });
      if (other.outcome !== "idempotency_key_reused") {
        fail(
          "keyreuse",
          `${u.id}: same key, other seat \u2192 ${other.outcome}, not idempotency_key_reused`
        );
      }
      const again = await reserve("keyreuse", u, [x], { key: k, shared: true });
      if (again.outcome !== "replayed" || idOf(again) !== idOf(first)) {
        fail(
          "keyreuse",
          `${u.id}: same key, same seat \u2192 ${again.outcome}, not a replay of the original`
        );
      }
    });
  }
  for (const u of takeUsers(o.limitUsers)) {
    const own = takeSeats(o.limitParallel);
    tasks.push(async () => {
      const rs = await Promise.all(own.map((s) => reserve("limit", u, [s])));
      const ok = rs.filter(isWin).length;
      const over2 = rs.filter((r) => r.outcome === "per_user_limit").length;
      const expect = Math.min(o.perUserLimit, own.length);
      if (ok !== expect || over2 !== own.length - expect) {
        fail(
          "limit",
          `${u.id}: ${ok} created, ${over2} per_user_limit (expected ${expect} and ${own.length - expect})`
        );
      }
    });
  }
  for (let i = 0; i < o.crossedPairs; i++) {
    const [a, b] = takeUsers(2);
    const [x, y] = takeSeats(2);
    tasks.push(async () => {
      const [ra, rb] = await Promise.all([
        reserve("crossed", a, [x, y]),
        reserve("crossed", b, [y, x])
      ]);
      const wins = [ra, rb].filter(isWin).length;
      const lost = [ra, rb].filter((r) => r.outcome === "seat_taken").length;
      if (wins !== 1 || lost !== 1) fail("crossed", `${x}+${y}: ${ra.outcome} / ${rb.outcome}`);
    });
  }
  for (const u of takeUsers(o.spoofs)) {
    const [seat] = takeSeats(1);
    tasks.push(async () => {
      const r = await reserve("spoof", u, [seat], { extra: { user_id: `${run}-victim` } });
      if (!isWin(r)) return fail("spoof", `${u.id}: ${r.outcome}`);
      const owner2 = r.body.user_id;
      if (owner2 !== u.id) fail("spoof", `${u.id}: booking recorded for ${owner2}`);
    });
  }
  for (let i = 0; i < o.foreignCancels; i++) {
    const [owner2, intruder] = takeUsers(2);
    const [seat] = takeSeats(1);
    tasks.push(async () => {
      const r = await reserve("foreign", owner2, [seat]);
      if (!isWin(r)) return fail("foreign", `${owner2.id}: ${r.outcome}`);
      const c2 = await call(
        "POST",
        `/reservations/${idOf(r)}/cancel`,
        { bearer: intruder.token },
        false
      );
      bump(scen.foreign, `cancel:${c2.outcome}`);
      if (c2.status !== 403)
        fail("foreign", `${intruder.id} cancelled ${owner2.id}'s booking: ${c2.status} ${c2.outcome}`);
    });
  }
  for (let i = tasks.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [tasks[i], tasks[j]] = [tasks[j], tasks[i]];
  }
  const pollViolations = [];
  let polls = 0;
  let pollFailed = 0;
  let sold = 0;
  let running = true;
  const checkSnapshot = (c2, where) => {
    const sum = c2.available + c2.held + c2.confirmed;
    if (!c2.invariant_ok || sum !== c2.total) {
      pollViolations.push(`${where}: ${c2.available}+${c2.held}+${c2.confirmed}=${sum} of ${c2.total}`);
    }
    if (c2.confirmed < sold)
      pollViolations.push(`${where}: sold went down ${sold} \u2192 ${c2.confirmed}`);
    sold = Math.max(sold, c2.confirmed);
  };
  const poller = (async () => {
    if (!o.pollMs) return;
    while (running && !signal?.aborted) {
      const r = await send("GET", showPath);
      if (r.status === 200) {
        polls++;
        checkSnapshot(r.body.counts, `poll ${polls}`);
      } else {
        pollFailed++;
        if (r.status >= 500 || r.status === 0) httpStatus[r.status === 0 ? "network" : "5xx"]++;
      }
      await sleep(o.pollMs, signal);
    }
  })();
  const mark = await send("GET", "/ops/logs?limit=1");
  const logSeq = mark.body?.lines?.at(-1)?.seq ?? 0;
  const t0 = performance.now();
  const planned = plannedRequests(o);
  const ticker = setInterval(() => {
    o.onProgress?.({
      elapsedMs: performance.now() - t0,
      done,
      planned,
      inFlight,
      outcomes: { ...outcomes },
      polls,
      pollViolations: pollViolations.length
    });
  }, 250);
  status(`firing ${planned.toLocaleString("en")} requests, ${o.concurrency} in flight\u2026`);
  try {
    await Promise.all(tasks.map((t) => t()));
  } finally {
    running = false;
    clearInterval(ticker);
  }
  const durationMs = performance.now() - t0;
  await poller;
  o.onProgress?.({
    elapsedMs: durationMs,
    done,
    planned,
    inFlight: 0,
    outcomes: { ...outcomes },
    polls,
    pollViolations: pollViolations.length
  });
  status("reconciling\u2026");
  const snap = await send("GET", showPath);
  const finalSnap = snap.status === 200 ? snap.body : null;
  if (finalSnap) checkSnapshot(finalSnap.counts, "final");
  const auditR = await send("GET", `${showPath}/audit`);
  const audit = auditR.status === 200 ? auditR.body : null;
  const serverAfter = await instanceNow();
  let metrics = null;
  if (metricsBefore) {
    const m = await fetch(`${base2}/metrics`, { signal }).catch(() => null);
    const after = m?.ok ? reserveCounters(parseMetrics(await m.text())) : null;
    if (after) {
      const keys = /* @__PURE__ */ new Set([...Object.keys(outcomes), ...after.keys()]);
      metrics = [...keys].map((k) => ({
        outcome: k,
        observed: outcomes[k] ?? 0,
        delta: (after.get(k) ?? 0) - (metricsBefore.get(k) ?? 0)
      })).filter((r) => r.observed || r.delta).sort((a, b) => b.observed - a.observed);
    }
  }
  const checks = [];
  const check = (name2, ok, detail) => checks.push({ name: name2, ok, detail });
  let causes = "";
  if (httpStatus["5xx"] > 0) {
    const logs = await send("GET", `/ops/logs?level=error&after=${logSeq}&limit=200`);
    const lines = logs.body?.lines;
    const seen = /* @__PURE__ */ new Map();
    for (const l of lines ?? []) {
      const f = l.fields ?? {};
      const err = f.err;
      if (!err) continue;
      const what = String(f.code ?? l.msg ?? f.status);
      const why = `${what} \u2190 ${err.code ?? ""} ${err.message ?? ""}`.trim();
      seen.set(why, (seen.get(why) ?? 0) + 1);
    }
    if (seen.size) causes = `: ${[...seen].map(([why, n2]) => `${why} (\xD7${n2})`).join("; ")}`;
  }
  check(
    "no 5xx",
    httpStatus["5xx"] === 0,
    `${httpStatus["5xx"]} server errors (polls included)${causes}`
  );
  const span = (a, b) => Math.round(a) === Math.round(b) ? `${Math.round(a)}ms` : `${Math.round(a)}\u2013${Math.round(b)}ms`;
  check(
    "every request answered",
    unanswered === 0,
    (unanswered ? `${unanswered} still unanswered after ${MAX_ATTEMPTS} tries; ` : httpStatus.network ? "" : "no connection dropped") + (httpStatus.network ? `${httpStatus.network} connections dropped in transit after ${span(netMin, netMax)}` + (unanswered ? "" : ", each reserve and cancel retried with the same key and answered") + (networkErrors.length ? `: ${networkErrors.join("; ")}` : "") : "")
  );
  if (serverBefore && serverAfter) {
    const same = serverBefore.instance === serverAfter.instance && serverBefore.started_at === serverAfter.started_at;
    check(
      "server stayed up",
      same,
      same ? `instance ${serverBefore.instance}, up since ${serverBefore.started_at}` : `${serverBefore.instance} (up since ${serverBefore.started_at}) \u2192 ${serverAfter.instance} (up since ${serverAfter.started_at})`
    );
  }
  const owner = /* @__PURE__ */ new Map();
  const doubles = [];
  for (const g of granted) {
    for (const s of g.seats) {
      const prev = owner.get(s);
      if (prev && prev !== g.reservation_id) doubles.push(s);
      owner.set(s, g.reservation_id);
    }
  }
  const distinct = new Set(granted.map((g) => g.reservation_id)).size;
  check(
    "no seat sold twice",
    doubles.length === 0,
    doubles.length ? `seats in two reservations: ${doubles.slice(0, 10).join(", ")}` : `${owner.size.toLocaleString("en")} seats across ${distinct.toLocaleString("en")} reservations, all disjoint`
  );
  const perUser = /* @__PURE__ */ new Map();
  for (const g of new Map(granted.map((x) => [x.reservation_id, x])).values()) {
    perUser.set(g.user_id, (perUser.get(g.user_id) ?? 0) + g.seats.length);
  }
  const over = [...perUser].filter(([, n2]) => n2 > o.perUserLimit);
  check(
    "no user over the limit",
    over.length === 0,
    over.length ? over.slice(0, 5).map(([u, n2]) => `${u} holds ${n2}`).join(", ") : `max ${Math.max(0, ...perUser.values())} of ${o.perUserLimit} seats per user`
  );
  if (finalSnap) {
    const sold2 = new Set(
      finalSnap.seats.filter((s) => s.status !== "available").map((s) => s.label)
    );
    const missing = [...owner.keys()].filter((s) => !sold2.has(s));
    const extra = [...sold2].filter((s) => !owner.has(s));
    check(
      "final map matches what was granted",
      missing.length === 0 && extra.length === 0 && finalSnap.counts.held === 0,
      missing.length || extra.length ? `granted but not sold: ${missing.slice(0, 5).join(", ") || "none"}; sold but never granted: ${extra.slice(0, 5).join(", ") || "none"}` : `${sold2.size.toLocaleString("en")} sold = ${owner.size.toLocaleString("en")} granted`
    );
  } else {
    check("final map matches what was granted", false, `GET ${showPath} \u2192 ${snap.status}`);
  }
  check(
    "invariant held during the burst",
    pollViolations.length === 0 && (polls > 0 || !o.pollMs),
    pollViolations.length ? pollViolations.slice(0, 3).join("; ") : `${polls} snapshots, every one balanced${pollFailed ? ` (${pollFailed} polls failed)` : ""}`
  );
  check(
    "audit",
    audit?.ok === true,
    audit ? audit.ok ? "ok" : JSON.stringify(audit.violations).slice(0, 200) : `HTTP ${auditR.status}`
  );
  const hotWins = scen.hot.created ?? 0;
  const hotOdd = Object.keys(scen.hot).filter((k) => !["created", "seat_taken"].includes(k));
  check(
    "hot: one winner per hot seat",
    hotWins === hotWanted.size && hotOdd.length === 0,
    `${hotWins} winners for ${hotWanted.size} seats among ${o.hotUsers} users` + (hotOdd.length ? `; unexpected ${hotOdd.join(", ")}` : "")
  );
  const stampedeOdd = Object.keys(scen.stampede).filter(
    // "overloaded": still shed after every retry. A 429 is graceful degradation, not a broken
    // guarantee; it is listed in the detail and in the outcome table.
    (k) => !["created", "seat_taken", "per_user_limit", "overloaded"].includes(k)
  );
  check(
    "stampede: only bookings and clean declines",
    stampedeOdd.length === 0,
    stampedeOdd.length ? `unexpected outcomes: ${stampedeOdd.map((k) => `${k}\xD7${scen.stampede[k]}`).join(", ")}` : Object.entries(scen.stampede).map(([k, v]) => `${k} ${v.toLocaleString("en")}`).join(" \xB7 ")
  );
  const exactScenarios = [
    ["retry", "same key: one booking, the rest replay it", o.retryGroups],
    ["keyreuse", "key reuse: 409, then the original replays", o.keyReuseGroups],
    ["limit", `limit: exactly ${o.perUserLimit} of ${o.limitParallel} parallel`, o.limitUsers],
    ["crossed", "crossed pairs: one winner, no deadlock", o.crossedPairs],
    ["spoof", "spoofed user_id ignored", o.spoofs],
    ["foreign", "foreign cancel refused (403)", o.foreignCancels]
  ];
  for (const [s, label, n2] of exactScenarios) {
    if (n2 === 0) continue;
    check(
      label,
      failures[s].length === 0,
      failures[s].length ? failures[s].join("; ") : `${n2} groups as expected`
    );
  }
  if (metrics) {
    const behind = metrics.filter((m) => m.delta < m.observed);
    const ahead = metrics.filter((m) => m.delta > m.observed);
    const lost = ahead.reduce((a, m) => a + m.delta - m.observed, 0);
    const mayLose = droppedAttempts + resent;
    const off = [...behind, ...lost > mayLose ? ahead : []];
    const lostNote = `${lost} answer${lost === 1 ? "" : "s"} the server sent never arrived (${ahead.map((m) => `${m.outcome} +${m.delta - m.observed}`).join(", ")})`;
    check(
      "metrics match observations",
      off.length === 0,
      off.length ? off.map((m) => `${m.outcome}: saw ${m.observed}, metric +${m.delta}`).join("; ") + (lost > mayLose ? `; more than the ${mayLose} requests whose answer was lost in transit` : "") : lost ? `fdfs_reserve_responses_total agrees on ${metrics.length - ahead.length} of ${metrics.length} outcomes; ${lostNote}, within the ${mayLose} requests whose answer was lost in transit` : `fdfs_reserve_responses_total agrees on all ${metrics.length} outcomes`
    );
  }
  const sortedLat = latencies.sort((a, b) => a - b);
  const report = {
    ok: checks.every((c2) => c2.ok),
    show,
    base: o.base,
    durationMs,
    outcomes,
    scenarios: scen,
    status: httpStatus,
    retries,
    unanswered,
    resent,
    reserveRequests,
    throughput: reserveRequests / Math.max(1e-3, durationMs / 1e3),
    latency: sortedLat.length ? {
      p50: quantile(sortedLat, 0.5),
      p95: quantile(sortedLat, 0.95),
      p99: quantile(sortedLat, 0.99),
      max: sortedLat.at(-1)
    } : null,
    slowest,
    polls: { count: polls, violations: pollViolations, failed: pollFailed },
    final: finalSnap?.counts ?? null,
    audit,
    metrics,
    checks
  };
  const saved = await send("POST", "/ops/runs", {
    bearer: o.adminKey,
    body: { ...report, settings: { concurrency: o.concurrency, perUserLimit: o.perUserLimit } }
  });
  if (saved.status !== 201) {
    status(
      `note: could not record the run for the War Room (HTTP ${saved.status} ${saved.outcome})`
    );
  }
  return report;
}

// scripts/burst/burst.ts
var HELP = `Usage: node burst.mjs <BASE_URL> [options]    (or, in a clone: npm run burst -- <BASE_URL>)

  --admin-key <key>      admin key for POST /shows (default: $ADMIN_API_KEY)
  --requests <n>         stampede requests (default ${DEFAULTS.requests})
  --users <n>            stampede crowd size (default ${DEFAULTS.users})
  --concurrency <n>      requests in flight (default ${DEFAULTS.concurrency})
  --rows <n>             hall rows (default ${DEFAULTS.rows})
  --seats-per-row <n>    hall seats per row (default ${DEFAULTS.seatsPerRow})
  --limit <n>            per-user seat limit (default ${DEFAULTS.perUserLimit})
  --hot-users <n>        users storming the hot seats (default ${DEFAULTS.hotUsers})
  --small                a quick run: 2,000 stampede requests, smaller scenarios
  --no-metrics           skip the /metrics diff (another client is booking on the same instance)
  --json <file>          also write the full report as JSON
  -h, --help`;
function int(v, name, fallback) {
  if (v === void 0) return fallback;
  const n2 = Number(v);
  if (!Number.isInteger(n2) || n2 < 0) throw new Error(`--${name} must be a whole number`);
  return n2;
}
var { values, positionals } = parseArgs({
  allowPositionals: true,
  options: {
    "admin-key": { type: "string" },
    requests: { type: "string" },
    users: { type: "string" },
    concurrency: { type: "string" },
    rows: { type: "string" },
    "seats-per-row": { type: "string" },
    limit: { type: "string" },
    "hot-users": { type: "string" },
    small: { type: "boolean", default: false },
    "no-metrics": { type: "boolean", default: false },
    json: { type: "string" },
    help: { type: "boolean", short: "h", default: false }
  }
});
if (values.help || positionals.length !== 1) {
  console.log(HELP);
  process.exit(values.help ? 0 : 2);
}
var base = positionals[0];
var adminKey = values["admin-key"] ?? process.env.ADMIN_API_KEY ?? "";
if (!adminKey) {
  console.error("An admin key is required: --admin-key <key> or ADMIN_API_KEY.");
  process.exit(2);
}
var small = values.small ? {
  requests: 2e3,
  users: 600,
  hotUsers: 100,
  retryGroups: 20,
  keyReuseGroups: 10,
  limitUsers: 5,
  crossedPairs: 10,
  spoofs: 10,
  foreignCancels: 10,
  rows: 20,
  seatsPerRow: 30
} : {};
var opts = { ...DEFAULTS, ...small };
opts.requests = int(values.requests, "requests", opts.requests);
opts.users = int(values.users, "users", opts.users);
opts.concurrency = int(values.concurrency, "concurrency", opts.concurrency);
opts.rows = int(values.rows, "rows", opts.rows);
opts.seatsPerRow = int(values["seats-per-row"], "seats-per-row", opts.seatsPerRow);
opts.perUserLimit = int(values.limit, "limit", opts.perUserLimit);
opts.hotUsers = int(values["hot-users"], "hot-users", opts.hotUsers);
opts.metrics = !values["no-metrics"];
var tty = process.stdout.isTTY;
var c = (code) => (s) => tty ? `\x1B[${code}m${s}\x1B[0m` : s;
var [green, red, yellow, dim, bold] = [c(32), c(31), c(33), c(2), c(1)];
var n = (v) => v.toLocaleString("en");
var ms = (v) => v >= 1e3 ? `${(v / 1e3).toFixed(2)}s` : `${Math.round(v)}ms`;
var row = (cells, widths) => cells.map((x, i) => i === 0 ? x.padEnd(widths[i]) : x.padStart(widths[i])).join("  ");
function print(r) {
  const out = [];
  out.push("");
  out.push(bold(`Burst against ${r.base}`));
  out.push(dim(`show ${r.show.id} \xB7 ${n(r.show.total_seats)} seats \xB7 ${ms(r.durationMs)}`));
  out.push("", bold("Reserve outcomes") + dim(" (every response, retries included)"));
  const total = Object.values(r.outcomes).reduce((a, b) => a + b, 0);
  for (const [k, v] of Object.entries(r.outcomes).sort((a, b) => b[1] - a[1])) {
    out.push("  " + row([k, n(v), `${(v / Math.max(1, total) * 100).toFixed(1)}%`], [24, 8, 7]));
  }
  out.push(
    "  " + row(["429 shed / retried", `${n(r.status["429"])} / ${n(r.retries)}`, ""], [24, 8, 7])
  );
  out.push(
    "  " + row(
      [
        "5xx \xB7 dropped \xB7 unanswered",
        `${n(r.status["5xx"])} \xB7 ${n(r.status.network)} \xB7 ${n(r.unanswered)}`,
        ""
      ],
      [24, 8, 7]
    )
  );
  if (r.resent) {
    out.push("  " + row(["re-sent in transit", n(r.resent), ""], [24, 8, 7]));
  }
  out.push("", bold("By scenario") + dim(" (final outcome per request)"));
  for (const [s, rec] of Object.entries(r.scenarios)) {
    const parts = Object.entries(rec).sort((a, b) => b[1] - a[1]).map(([k, v]) => `${k} ${n(v)}`);
    if (parts.length) out.push(`  ${s.padEnd(10)} ${parts.join(" \xB7 ")}`);
  }
  out.push("", bold("Speed"));
  out.push(`  ${n(r.reserveRequests)} reserve requests at ${r.throughput.toFixed(0)} req/s`);
  if (r.latency) {
    const l = r.latency;
    out.push(`  p50 ${ms(l.p50)} \xB7 p95 ${ms(l.p95)} \xB7 p99 ${ms(l.p99)} \xB7 max ${ms(l.max)}`);
  }
  if (r.slowest.length) {
    out.push(dim(`  slowest (x-request-id, searchable in the War Room log tail):`));
    for (const s of r.slowest) out.push(dim(`    ${s.requestId}  ${ms(s.ms)}  ${s.outcome}`));
  }
  if (r.final) {
    const f = r.final;
    out.push("", bold("Final reconciliation"));
    out.push(
      `  ${n(f.available)} available + ${n(f.held)} held + ${n(f.confirmed)} sold = ${n(f.available + f.held + f.confirmed)} of ${n(f.total)}`
    );
  }
  if (r.metrics) {
    out.push("", bold("/metrics vs observed") + dim(" (fdfs_reserve_responses_total delta)"));
    const within = r.checks.find((ch) => ch.name === "metrics match observations")?.ok;
    for (const m of r.metrics) {
      const mark = m.observed === m.delta ? green("=") : within && m.delta > m.observed ? yellow("\u2248") : red("\u2260");
      out.push("  " + row([m.outcome, n(m.observed), mark, n(m.delta)], [24, 8, 1, 8]));
    }
  }
  out.push("", bold("Checks"));
  for (const ch of r.checks) {
    out.push(`  ${ch.ok ? green("\u2713") : red("\u2717")} ${ch.name.padEnd(44)} ${dim(ch.detail)}`);
  }
  out.push("");
  out.push(
    r.ok ? green(bold("PASS: every guarantee held.")) : red(bold("FAIL: see the checks above."))
  );
  console.log(out.join("\n"));
}
var ctrl = new AbortController();
process.once("SIGINT", () => {
  console.error("\ninterrupted");
  ctrl.abort();
  process.exit(130);
});
var lastLine = 0;
try {
  console.log(
    dim(
      `${n(plannedRequests({ ...DEFAULTS, ...opts }))} requests planned, ${opts.concurrency} in flight`
    )
  );
  const report = await runBurst({
    ...opts,
    base,
    adminKey,
    signal: ctrl.signal,
    onStatus: (line) => console.log(dim(line)),
    onShow: (s) => console.log(dim(`show ${s.id}: ${base.replace(/\/+$/, "")}/app/shows/${s.id}`)),
    onProgress: (p) => {
      if (p.elapsedMs - lastLine < 2e3 && p.done < p.planned) return;
      lastLine = p.elapsedMs;
      const pct = Math.min(100, p.done / Math.max(1, p.planned) * 100).toFixed(0);
      const seen = Object.entries(p.outcomes).sort((a, b) => b[1] - a[1]).slice(0, 4).map(([k, v]) => `${k} ${n(v)}`).join(" \xB7 ");
      console.log(
        dim(
          `  ${(p.elapsedMs / 1e3).toFixed(0).padStart(4)}s  ${pct.padStart(3)}%  ${n(p.done)} done  ${p.inFlight} in flight  ${seen}  \xB7 ${p.polls} polls${p.pollViolations ? red(` ${p.pollViolations} unbalanced`) : ""}`
        )
      );
    }
  });
  print(report);
  if (values.json) await writeFile(values.json, JSON.stringify(report, null, 2));
  process.exit(report.ok ? 0 : 1);
} catch (err) {
  console.error(red(`burst failed: ${err.message}`));
  process.exit(1);
}
